# /src/menus/layer/ xml files

xml_sources_menus_layer = files(
    'alpha-add.xml',
    'alpha-remove.xml',
    'alpha-selection-add.xml',
    'alpha-selection-intersect.xml',
    'alpha-selection-replace.xml',
    'alpha-selection-subtract.xml',
    'alpha-semi-flatten.xml',
    'anchor.xml',
    'bottom.xml',
    'color-to-alpha.xml',
    'crop-to-content.xml',
    'delete.xml',
    'duplicate.xml',
    'flip-horizontal.xml',
    'flip-vertical.xml',
    'introduction.xml',
    'lower-to-bottom.xml',
    'lower.xml',
    'mask-add.xml',
    'mask-apply.xml',
    'mask-delete.xml',
    'mask-disable.xml',
    'mask-edit.xml',
    'mask-selection-add.xml',
    'mask-selection-intersect.xml',
    'mask-selection-replace.xml',
    'mask-selection-subtract.xml',
    'mask-show.xml',
    'mask.xml',
    'merge-down.xml',
    'merge-layer-group.xml',
    'new-from-visible.xml',
    'new-layer-group.xml',
    'new.xml',
    'next.xml',
    'offset.xml',
    'previous.xml',
    'raise-to-top.xml',
    'raise.xml',
    'resize-to-image.xml',
    'resize-to-selection.xml',
    'resize.xml',
    'rotate-180.xml',
    'rotate-270.xml',
    'rotate-90.xml',
    'rotate-arbitrary.xml',
    'scale.xml',
    'stack-reverse.xml',
    'stack.xml',
    'text-along-path.xml',
    'text-commands.xml',
    'text-discard.xml',
    'text-to-path.xml',
    'threshold-alpha.xml',
    'top.xml',
    'transform.xml',
    'transparency.xml',
)
