# /src/menus/ xml files

xml_sources_menus = files(
    'about-plugin-menuitems.xml',
    'colors.xml',
    'edit.xml',
    'file.xml',
    'filters.xml',
    'help.xml',
    'image.xml',
    'introduction.xml',
    'layer.xml',
    'select.xml',
    'tools.xml',
    'view.xml',
    'windows-open-recent-docks.xml',
    'windows.xml',
)

subdir('colors')
subdir('edit')
subdir('file')
subdir('filters')
subdir('help')
subdir('image')
subdir('layer')
subdir('select')
subdir('view')
