# /src/dialogs/ xml files

xml_sources_dialogs = files(
    'brushes-dialog.xml',
    'buffers-dialog.xml',
    'channel-dialog.xml',
    'channel-menu.xml',
    'channel-selection-mask.xml',
    'color-dialog.xml',
    'common-export-as-cmyk-setting.xml',
    'common-metadata-settings.xml',
    'dashboard.xml',
    'device-status-dialog.xml',
    'dialogs-content.xml',
    'dialogs-file.xml',
    'dialogs-management.xml',
    'dialogs-misc.xml',
    'dialogs-preferences.xml',
    'dialogs-structure.xml',
    'dialogs_introduction.xml',
    'document-dialog.xml',
    'edit-template-dialog.xml',
    'eps-ps-common-options.xml',
    'error-console.xml',
    'export-file-dialog.xml',
    'export-file-formats.xml',
    'file-aa-export.xml',
    'file-ani-export.xml',
    'file-bmp-export.xml',
    'file-cel-export.xml',
    'file-colorxhtml-export.xml',
    'file-csource-export.xml',
    'file-cur-export.xml',
    'file-dds-export.xml',
    'file-dicom-export.xml',
    'file-eps-export.xml',
    'file-exr-export.xml',
    'file-farbfeld-export.xml',
    'file-fits-export.xml',
    'file-fli-export.xml',
    'file-gbr-export.xml',
    'file-gif-export.xml',
    'file-gih-export.xml',
    'file-header-export.xml',
    'file-heif-export.xml',
    'file-heif-av1-export.xml',
    'file-heif-hej2-export.xml',
    'file-html-table-export.xml',
    'file-icns-export.xml',
    'file-ico-export.xml',
    'file-jpeg-export.xml',
    'file-jpegxl-export.xml',
    'file-jp2-export.xml',
    'file-j2k-export.xml',
    'file-mng-export.xml',
    'file-ora-export.xml',
    'file-pat-export.xml',
    'file-pcx-export.xml',
    'file-pdf-export.xml',
    'file-pfm-export.xml',
    'file-pix-export.xml',
    'file-png-export.xml',
    'file-pnm-export.xml',
    'file-ps-export.xml',
    'file-psd-export.xml',
    'file-qoi-export.xml',
    'file-raw-export.xml',
    'file-rgbe-export.xml',
    'file-sgi-export.xml',
    'file-sunras-export.xml',
    'file-svg-export.xml',
    'file-tga-export.xml',
    'file-tiff-export.xml',
    'file-tim-export.xml',
    'file-xbm-export.xml',
    'file-xmc-export.xml',
    'file-xpm-export.xml',
    'file-xwd-export.xml',
    'file-webp-export.xml',
    'fonts-dialog.xml',
    'gradient-dialog.xml',
    'gradient-editor-dialog.xml',
    'heif-avif-common-options.xml',
    'histogram-dialog.xml',
    'images-dialog.xml',
    'import-file-formats.xml',
    'indexed-palette-dialog.xml',
    'jpeg-2000-common-options.xml',
    'keyboard-shortcuts-dialog.xml',
    'layer-dialog.xml',
    'layer-mask.xml',
    'mypaint-brushes-dialog.xml',
    'navigation-dialog.xml',
    'open-file-dialog.xml',
    'palettes-dialog.xml',
    'path-dialog.xml',
    'patterns-dialog.xml',
    'pointer-dialog.xml',
    'prefs-canvas-interaction-modifiers.xml',
    'prefs-canvas-interaction-snapping.xml',
    'prefs-canvas-interaction.xml',
    'prefs-color-management.xml',
    'prefs-debugging.xml',
    'prefs-default-grid.xml',
    'prefs-default-image.xml',
    'prefs-dialog-defaults.xml',
    'prefs-display.xml',
    'prefs-folders-data.xml',
    'prefs-folders.xml',
    'prefs-help.xml',
    'prefs-icon-theme.xml',
    'prefs-image-window-appearance.xml',
    'prefs-image-window-title.xml',
    'prefs-image-window.xml',
    'prefs-import-export.xml',
    'prefs-input-controllers.xml',
    'prefs-input-devices.xml',
    'prefs-interface.xml',
    'prefs-playground.xml',
    'prefs-system-resources.xml',
    'prefs-theme.xml',
    'prefs-tool-options.xml',
    'prefs-toolbox.xml',
    'prefs-window-management.xml',
    'qmask.xml',
    'sample-points.xml',
    'save-file-dialog.xml',
    'symmetry-painting.xml',
    'tagging.xml',
    'templates-dialog.xml',
    'tool-preset-editor.xml',
    'tool-presets-dialog.xml',
    'undo-history-dialog.xml',
    'welcome-dialog.xml',
)
