# /src/menus/help/ xml files

xml_sources_menus_help = files(
    'about.xml',
    'context-help.xml',
    'gimp-online.xml',
    'help.xml',
    'introduction.xml',
    'plug-in-browser.xml',
    'plug-in-gegl-filter-browser.xml',
    'procedure-browser.xml',
    'search-and-run.xml',
    'tip-of-the-day.xml',
    'user-manual.xml',
    'welcome-dialog.xml',
)
