# common images (and fonts), the same for all languages


images_common = files(
    'caution.png',
    'draft.png',
    'example.png',
    'gimp-org.png',
    'gimp-splash.png',
    'home.png',
    'important.png',
    'link.png',
    'mousebutton.png',
    'next.png',
    'note.png',
    'prev.png',
    'tip.png',
    'up.png',
    'warning.png',
)

subdir('fonts')

images_common_files = \
    images_common + \
    images_common_fonts
