# /src/filters/blur/ xml files

xml_sources_filters_blur = files(
    'circular-motion.xml',
    'focus-blur.xml',
    'gauss.xml',
    'gauss_select.xml',
    'introduction.xml',
    'lens-blur.xml',
    'linear-motion.xml',
    'mean-curvature-blur.xml',
    'median-blur.xml',
    'pixelize.xml',
    'tileable.xml',
    'variable-blur.xml',
    'zoom-motion.xml',
)
