# /src/menus/select/ xml files

xml_sources_menus_select = files(
    'all.xml',
    'border.xml',
    'by_color.xml',
    'distort.xml',
    'feather.xml',
    'float.xml',
    'from-path.xml',
    'grow.xml',
    'introduction.xml',
    'invert.xml',
    'none.xml',
    'qmask-toggle.xml',
    'remove-holes.xml',
    'rounded-rectangle.xml',
    'selection-editor.xml',
    'sharpen.xml',
    'shrink.xml',
    'to-channel.xml',
    'to-path.xml',
)
