image: debian:testing

stages:
  - build

variables:
  INSTALL_DIR: "_install"
  INSTALL_PREFIX: "${CI_PROJECT_DIR}/${INSTALL_DIR}"
  LINGUAS: "en nl"

build-debian:
  stage: build
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - www/
    - html/
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends
        automake
        build-essential
        dblatex
        docbook-website
        docbook-xml
        docbook-xsl
        fonts-freefont-otf
        gettext
        pkg-config
        pngcrush
        pngnq
        python3
        python3-libxml2
        texlive-fonts-recommended
        texlive-lang-all
        texlive-xetex
        xsltproc
  script:
    - mkdir _build
    - cd _build
    - ../autogen.sh --prefix=${INSTALL_PREFIX} --without-gimp
    - make pdf-en && make install
    - mv ${INSTALL_PREFIX}/share/gimp/2.0/help/ ../www/
    - cd ../web
    - make
    - mv html/ ../html/
  timeout: 2 hours
