image: debian:testing

stages:
  - build

variables:
  INSTALL_DIR: "_install"
  INSTALL_PREFIX: "${CI_PROJECT_DIR}/${INSTALL_DIR}"
  LINGUAS: "en"

build-debian:
  stage: build
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - www/
    - html/
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends
        automake
        build-essential
        docbook-website
        docbook-xml
        docbook-xsl
        gettext
        librsvg2-2
        librsvg2-bin
        pkg-config
        pngcrush
        pngnq
        python3
        python3-libxml2
        xsltproc
  script:
    - mkdir _build
    - cd _build
    - ../autogen.sh --prefix=${INSTALL_PREFIX} --without-gimp
    - make && make install
    - mv ${INSTALL_PREFIX}/share/gimp/2.0/help/ ../www/
    - cd ../web
    - make
    - mv /html/ ../html/
    - cd ../_build
    - mv /quickreference/pdf/ ../html/2.10/pdf/
  timeout: 2 hours 30 minutes
