image: debian:testing

stages:
  - build

variables:
  INSTALL_DIR: "_install"
  INSTALL_PREFIX: "${CI_PROJECT_DIR}/${INSTALL_DIR}"
  LINGUAS: "en nl"

build-debian:
  stage: build
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - dist/
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends
        automake
        build-essential
        docbook-website
        docbook-xml
        docbook-xsl
        gettext
        librsvg2-2
        librsvg2-bin
        pkg-config
        pngcrush
        pngnq
        python3
        python3-libxml2
        xsltproc
  script:
    - mkdir dist
    - mkdir _build
    - cd _build
    - ../autogen.sh --prefix=${INSTALL_PREFIX} --without-gimp
    - make dist
    - mv ./config.* ../dist/
    - mv ./gimp-help-2.10.30.tar.* ../dist/
  timeout: 2 hours 30 minutes
