---
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build the documentation and translations
    init: |
      mkdir _build
      cd _build
      ../autogen.sh --prefix=${INSTALL_PREFIX} --without-gimp
      make
