# What to build

# All languages can take a long time to build and is not recommended for general use
option('languages', type : 'string', value : 'all', description : 'Select the language codes separated by a space; or "all" for all languages')

# Build website and maintainer related targets
option('maintainer', type : 'boolean', value : false)

# Build quickreference PDF files
option('quickreference', type : 'boolean', value : false)
