# /src/menus/image/ xml files

xml_sources_menus_image = files(
    'align-layers.xml',
    'assign-color-profile.xml',
    'canvas-size.xml',
    'color-management.xml',
    'configure-grid.xml',
    'convert-grayscale.xml',
    'convert-indexed.xml',
    'convert-rgb.xml',
    'convert-to-color-profile.xml',
    'crop.xml',
    'discard-color-profile.xml',
    'duplicate.xml',
    'encoding.xml',
    'fit-canvas-to-layers.xml',
    'fit-canvas-to-selection.xml',
    'flatten.xml',
    'guides-new-percent.xml',
    'guides-new-selection.xml',
    'guides-new.xml',
    'guides-remove.xml',
    'guides.xml',
    'introduction.xml',
    'merge-layers.xml',
    'metadata-editor.xml',
    'metadata-viewer.xml',
    'metadata.xml',
    'mode.xml',
    'print-size.xml',
    'properties.xml',
    'save-color-profile-to-file.xml',
    'scale.xml',
    'slice-using-guides.xml',
    'soft-proof-black-point.xml',
    'soft-proof-profile-assign.xml',
    'soft-proof-rendering-intent.xml',
    'transform-flip.xml',
    'transform-rotate.xml',
    'transform.xml',
    'use-srgb-profile.xml',
    'zealous-crop.xml',
)
