# /src/filters/distort/ xml files

xml_sources_filters_distort = files(
    'apply_lens.xml',
    'blinds.xml',
    'curve_bend.xml',
    'emboss.xml',
    'engrave.xml',
    'introduction.xml',
    'kaleidoscope.xml',
    'lens-distortion.xml',
    'mosaic.xml',
    'newsprint.xml',
    'pagecurl.xml',
    'polarcoords.xml',
    'ripple.xml',
    'shift.xml',
    'spherize.xml',
    'video-degradation.xml',
    'vpropagate.xml',
    'waves.xml',
    'whirlpinch.xml',
    'wind.xml',
)
