# generate to per language images, but if language has replacements then
# those replacement translated images need to be used instead of the
# versions here!

subdir('base-examples')
subdir('contribute')
subdir('dialogs')
subdir('filters')
subdir('glossary')
subdir('math')
subdir('menus')
subdir('preferences')
subdir('stock-icons')
subdir('tool-options')
subdir('toolbox')
subdir('tutorials')
subdir('using')

# FIXME Maybe we can add a tool in the future that automatically generates
# the meson.build files under /images/C/ and have another validation tool
# that checks for missing images in the meson.build files
