# /src/filters/artistic/ xml files

xml_sources_filters_artistic = files(
    'applycanvas.xml',
    'cartoon.xml',
    'clothify.xml',
    'cubism.xml',
    'GIMPressionist-orientmap.xml',
    'GIMPressionist-sizemap.xml',
    'GIMPressionist.xml',
    'glasstile.xml',
    'introduction.xml',
    'oilify.xml',
    'photocopy.xml',
    'simple-linear-clustering.xml',
    'softglow.xml',
    'vangogh-lic.xml',
    'waterpixels.xml',
    'weave.xml',
)
