# /src/toolbox/selection/ xml files

xml_sources_toolbox_selection = files(
    'about-common-select-modifiers.xml',
    'about-common-select-options.xml',
    'by-color.xml',
    'common-features.xml',
    'ellipse.xml',
    'foreground.xml',
    'free.xml',
    'fuzzy.xml',
    'iscissors.xml',
    'rectangle.xml',
)
