# /src/menus/colors/ xml files

xml_sources_menus_colors = files(
    'about-common-features.xml',
    'auto.xml',
    'brightness-contrast.xml',
    'color-balance.xml',
    'color-temperature.xml',
    'colorize.xml',
    'colortoalpha.xml',
    'components.xml',
    'curves.xml',
    'desaturate.xml',
    'dither.xml',
    'exposure.xml',
    'gegl-local-threshold.xml',
    'hot.xml',
    'hue-chroma.xml',
    'hue-saturation.xml',
    'info.xml',
    'introduction.xml',
    'invert.xml',
    'levels.xml',
    'linear-invert.xml',
    'map.xml',
    'posterize.xml',
    'rgb-clip.xml',
    'saturation.xml',
    'shadows-highlights.xml',
    'threshold.xml',
    'tone-mapping.xml',
    'value-invert.xml',
)

subdir('auto')
subdir('components')
subdir('desaturate')
subdir('info')
subdir('map')
subdir('tone-mapping')
