# /src/filters/render/ xml files

xml_sources_filters_render = files(
    'bayer-matrix.xml',
    'cell-noise.xml',
    'checkerboard-legacy.xml',
    'checkerboard.xml',
    'circuit.xml',
    'cmlexplorer.xml',
    'difference-clouds.xml',
    'diffraction.xml',
    'flame.xml',
    'fractalexplorer.xml',
    'gfig.xml',
    'grid-legacy.xml',
    'grid.xml',
    'ifsfractal.xml',
    'introduction.xml',
    'jigsaw.xml',
    'lava.xml',
    'line-nova.xml',
    'linear-sinusoid.xml',
    'maze.xml',
    'perlin-noise.xml',
    'plasma.xml',
    'qbist.xml',
    'simplex-noise.xml',
    'sinus.xml',
    'solid-noise.xml',
    'spheredesigner.xml',
    'spiral.xml',
    'spyrogimp.xml',
)
