# /src/filters/light-and-shadow/ xml files

xml_sources_filters_light = files(
    'bloom.xml',
    'drop-shadow-legacy.xml',
    'drop-shadow.xml',
    'gegl-bevel.xml',
    'gegl-inner-glow.xml',
    'gflare.xml',
    'introduction.xml',
    'lens-flare.xml',
    'lighting.xml',
    'long-shadow.xml',
    'perspective-shadow.xml',
    'sparkle.xml',
    'supernova.xml',
    'vignette.xml',
    'xach-effect.xml',
)
