# /src/concepts/ xml files

xml_sources_concepts = files(
    'basic-setup.xml',
    'brushes.xml',
    'color-management.xml',
    'concepts.xml',
    'docks.xml',
    'gradients.xml',
    'grid-and-guides.xml',
    'image-types.xml',
    'images-loading.xml',
    'images.xml',
    'imagewindow.xml',
    'intro.xml',
    'layer-effects.xml',
    'layer-groups.xml',
    'layer-modes-legacy.xml',
    'layer-modes.xml',
    'layer-types.xml',
    'layers.xml',
    'palettes.xml',
    'patterns.xml',
    'plugins.xml',
    'qmask.xml',
    'script-fu.xml',
    'selection.xml',
    'text-management.xml',
    'toolbox.xml',
    'tools-presets.xml',
    'undo.xml',
)
