subdir('C')
subdir('common')

images_C_files = \
    images_base_examples + \
    images_contribute + \
    images_dialogs + \
    images_dialogs_examples + \
    images_filters + \
    images_filters_animation + \
    images_filters_artistic + \
    images_filters_blur + \
    images_filters_combine + \
    images_filters_common + \
    images_filters_decor + \
    images_filters_distort + \
    images_filters_edge_detect + \
    images_filters_enhance + \
    images_filters_examples + \
    images_filters_examples_animation + \
    images_filters_examples_artistic + \
    images_filters_examples_blur + \
    images_filters_examples_decor + \
    images_filters_examples_distort + \
    images_filters_examples_edge_detect + \
    images_filters_examples_enhance + \
    images_filters_examples_generic + \
    images_filters_examples_light_and_shadow + \
    images_filters_examples_map + \
    images_filters_examples_noise + \
    images_filters_examples_render + \
    images_filters_generic + \
    images_filters_light_and_shadow + \
    images_filters_map + \
    images_filters_noise + \
    images_filters_render + \
    images_filters_web + \
    images_glossary + \
    images_math + \
    images_menus + \
    images_menus_colors + \
    images_menus_colors_auto + \
    images_menus_colors_components + \
    images_menus_colors_desaturate + \
    images_menus_colors_info + \
    images_menus_colors_map + \
    images_menus_colors_tone_mapping + \
    images_menus_edit + \
    images_menus_file + \
    images_menus_file_create + \
    images_menus_file_new + \
    images_menus_filters + \
    images_menus_help + \
    images_menus_image + \
    images_menus_image_color_management + \
    images_menus_layer + \
    images_menus_select + \
    images_menus_view + \
    images_menus_view_display_filters + \
    images_preferences + \
    images_stock_icons + \
    images_tool_options + \
    images_toolbox + \
    images_tutorials + \
    images_tutorials_tone_mapping + \
    images_using

images_common_files = \
    images_common + \
    images_common_fonts

# Original Makefile setting for updating/adding images:
# - lazy: fast and lazy: detect added or removed images, but may miss changed images
# - force: always update images
# - strict (default): detects added, removed, or changed images

# We are probably going to ignore this if we can figure out how to use
# meson directly to copy the images and leave symlinks for another time
# to figure out.
#image_update_flag = 'strict'

# We now always use what was called strict 9the default)
