subdir('C')
subdir('common')


# Original Makefile setting for updating/adding images:
# - lazy: fast and lazy: detect added or removed images, but may miss changed images
# - force: always update images
# - strict (default): detects added, removed, or changed images

# We are probably going to ignore this if we can figure out how to use
# meson directly to copy the images and leave symlinks for another time
# to figure out.
#image_update_flag = 'strict'

# We now always use what was called strict 9the default)
