# /src/toolbox/ xml files

xml_sources_toolbox = files(
    'about-common-options-display.xml',
    'color-picker.xml',
    'gegl-operation.xml',
    'intro.xml',
    'measure.xml',
    'other-tools.xml',
    'paint-tools.xml',
    'path.xml',
    'selection-tools.xml',
    'text.xml',
    'toolbox-color-area.xml',
    'transform-tools.xml',
    'zoom.xml',
)

subdir('paint')
subdir('selection')
subdir('transform')
