# /src/filters/map/ xml files

xml_sources_filters_map = files(
    'bumpmap.xml',
    'displace.xml',
    'fractal-trace.xml',
    'illusion.xml',
    'introduction.xml',
    'little-planet.xml',
    'map-object.xml',
    'panorama-projection.xml',
    'papertile.xml',
    'recursive-transform.xml',
    'smalltiles.xml',
    'tile-seamless.xml',
    'tile.xml',
    'warp.xml',
)
