# /src/filters/ xml files

xml_sources_filters = files(
    'about-common-features.xml',
    'animation.xml',
    'artistic.xml',
    'blur.xml',
    'combine.xml',
    'common-features.xml',
    'decor.xml',
    'distort.xml',
    'edge-detect.xml',
    'enhance.xml',
    'generic.xml',
    'include-distance-map-metric.xml',
    'introduction.xml',
    'light-and-shadow.xml',
    'map.xml',
    'noise.xml',
    'render.xml',
    'web.xml',
)

subdir('animation')
subdir('artistic')
subdir('blur')
subdir('combine')
subdir('decor')
subdir('distort')
subdir('edge-detect')
subdir('enhance')
subdir('generic')
subdir('light-and-shadow')
subdir('map')
subdir('noise')
subdir('render')
subdir('web')
