# /src/menus/edit/ xml files

xml_sources_menus_edit = files(
    'buffer.xml',
    'clear.xml',
    'copy-visible.xml',
    'copy.xml',
    'cut.xml',
    'fill-bg.xml',
    'fill-fg.xml',
    'fill-path.xml',
    'fill-pattern.xml',
    'fill-selection-outline.xml',
    'input-devices.xml',
    'introduction.xml',
    'module-manager.xml',
    'paste-as-brush.xml',
    'paste-as-floating-data-in-place.xml',
    'paste-as-floating-data.xml',
    'paste-as-new-image.xml',
    'paste-as-new-layer-in-place.xml',
    'paste-as-new-layer.xml',
    'paste-as-pattern.xml',
    'paste-as.xml',
    'paste-in-place.xml',
    'paste-into-selection-in-place.xml',
    'paste-into-selection.xml',
    'paste.xml',
    'preferences.xml',
    'redo.xml',
    'shortcuts.xml',
    'stroke-path.xml',
    'stroke-selection.xml',
    'undo-history.xml',
    'undo.xml',
    'units.xml',
)
