# /src/filters/enhance/ xml files

xml_sources_filters_enhance = files(
    'antialias.xml',
    'deinterlace.xml',
    'despeckle.xml',
    'high-pass.xml',
    'introduction.xml',
    'nl-filter.xml',
    'noise-reduction.xml',
    'red-eye-removal.xml',
    'symmetric-nearest-neighbor.xml',
    'unsharp_mask.xml',
    'wavelet-decompose.xml',
)
