#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
#
# generate_meson_build_po.py - Generates meson.build files for /src and images/
# Copyright (c) 2026 Jacob Boerema.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Based in part on validate_references.py

import os, sys
import re
import getopt

VERBOSE = False
VERSION = 0.1


# Regular expression for image files to be checked
IMAGEFILE_REGEX = re.compile(r'[\w.+-]*\.(png|jpg|svg|gif|apng|webp|jpeg)$')

# Meson code parts
first_lines      = "# This file is auto-generated by generate_meson_build.py.\n" + \
                   "# Do not change manually.\n\n"
code_line_start  = "    '"
code_line_end    = "',\n"
code_files_base  = " = files("
code_files       = " = files(\n"
code_files_end   = ")\n"
code_subdir      = "subdir('"
code_subdir_end  = "')\n"
code_array       = " = [\n"
code_array_end   = "]\n"

img_prune_dirs   = [ 'callouts', '.git' ]
src_prune_dirs   = [ 'images', '.git' ]

class BaseGenerator(object):
    def __init__(self, root_path, var_basename, prune_dirs):
        self.root_path  = root_path
        self.basename   = var_basename
        self.prune_dirs = prune_dirs
        self.header_extra_once = True
        self.extra_first_time  = True
        self.count_written     = 0

    def select_files(self, unfiltered_list):
        return unfiltered_list

    def generate_header_extra(self):
        return ''

    def generate_files_header(self, var_name):
        return var_name + code_files

    def generate_files_list(self, selected_names):
        contents = ''
        for filename in sorted(selected_names):
            contents += code_line_start + filename + code_line_end
        return contents

    def generate_files_footer(self):
        return code_files_end

    def generate_after_files(self, var_name):
        return ''

    def generate_subdirs(self, dirs):
        contents = "\n"
        for dir in sorted(dirs):
            contents += code_subdir + dir + code_subdir_end
        return contents

    def report(self):
        if VERBOSE:
            print(f"Files added/updated under {self.root_path}: {self.count_written}")

    def generate(self):
        for root, dirs, files in os.walk(self.root_path):
            for prune in self.prune_dirs:
                if prune in dirs:
                    dirs.remove(prune)

            file_contents  = first_lines
            file_contents += self.generate_header_extra()

            prefixlen = len(self.root_path)

            selected_names = self.select_files(files)

            if len(selected_names) > 0:
                # Determine name of variable
                var_name = self.basename + root[prefixlen:].replace("/", "_").replace("-", "_")
                if var_name.endswith('_'):
                    var_name += 'root'

                file_contents += self.generate_files_header(var_name)
                file_contents += self.generate_files_list(selected_names)
                file_contents += self.generate_files_footer()

                file_contents += self.generate_after_files(var_name)

            if len(dirs) > 0:
                file_contents += self.generate_subdirs(dirs)

            dest_file = root + '/meson.build'
            with open(dest_file, "w", encoding="utf-8", newline="\n") as f:
                f.write(file_contents)
                self.count_written += 1

        self.report()
        return True

class Generator4Image(BaseGenerator):

    def select_files(self, unfiltered_list):
        selected_names = []
        for name in unfiltered_list:
            if IMAGEFILE_REGEX.match(name):
                selected_names += [name]
            elif not name == 'meson.build' and VERBOSE:
                print(f"Ignored file: {name}")

        return selected_names

class Generator4Src(BaseGenerator):

    def select_files(self, unfiltered_list):
        selected_names = []
        for name in unfiltered_list:
            if name.endswith('.xml'):
                selected_names += [name]
            elif not name == 'meson.build' and VERBOSE:
                print(f"Ignored file: {name}")

        return selected_names

    def generate_header_extra(self):
        if not self.header_extra_once or self.extra_first_time:
            self.extra_first_time = False
            return "SRC_FOLDER = meson.current_source_dir()\n\n" + \
                "# We need access to the plain files without path\n"
        else:
            return ''

    def generate_files_header(self, var_name):
        return var_name + '_files' + code_array

    def generate_files_footer(self):
        return code_array_end

    def generate_after_files(self, var_name):
        return var_name + code_files_base + var_name + "_files)\n"

def printVersion():
    print(f"\ngenerate_meson_build.py v {VERSION}")

def usage():
    printVersion()
    print("""Generates updated meson.build files for images/C/ and src/.

usage: generate_meson_build.py [options] gimp-help source directory

    options:
                --no-image      disable generating meson.build files for images
                --no-src        disable generating meson.build files for src
        -v      --verbose       be more verbose
        -h      --help          this help""")

def main(argv):
    # gimp-help directories
    src_dir   = 'src/'
    image_dir = 'images/C/'
    # default assume current directory is root_dir
    root_dir  = '.'
    # default assume we want both images and src
    src_enabled = True
    img_enabled = True
    global VERBOSE

    try:
        opts, remaining_args = getopt.getopt(argv, "hv",
            [
                "help", "no-image", "no-src", "verbose"
            ])
    except getopt.GetoptError as err:
        usage()
        sys.exit(1)

    for opt, arg in opts:
        if opt == "-h" or opt == "--help":
            usage()
            sys.exit(0)
        elif opt == "--no-image":
            img_enabled = False
        elif opt == "--no-src":
            src_enabled = False
        elif opt == "-v" or opt == "--verbose":
            VERBOSE = True

    if remaining_args is not None and len(remaining_args) == 1:
        root_dir = remaining_args[0]

    root_dir = os.path.abspath(root_dir)
    if not (root_dir.endswith("/") or root_dir.endswith("\\")):
        root_dir += '/'

    img_root = root_dir + image_dir
    src_root = root_dir + src_dir

    if img_enabled and os.path.exists(img_root):
        files_basename   = 'images_'

        img_generator = Generator4Image(img_root, files_basename, img_prune_dirs)
        img_generator.generate()
    elif img_enabled:
        print(f"Image root folder {img_root} not found!")

    if src_enabled and os.path.exists(src_root):
        files_basename   = 'xml_sources_'

        src_generator = Generator4Src(src_root, files_basename, src_prune_dirs)
        src_generator.generate()
    elif src_enabled:
        print(f"Source xml root folder {src_root} not found!")


if __name__ == "__main__":
    main(sys.argv[1:])
