message('src submenu')

SRC_FOLDER = meson.current_source_dir()

xml_sources_root = files(
    'gimp.xml',
    'help-missing.xml',
    'introduction.xml',
    'key-reference.xml',
)

subdir('appendix')
subdir('concepts')
subdir('dialogs')
subdir('filters')
subdir('glossary')
#subdir('images')
subdir('introduction')
subdir('menus')
subdir('preface')
subdir('toolbox')
subdir('tutorial')
subdir('using')
