message('src submenu')

SRC_FOLDER = meson.current_source_dir()

# We need access to the plain files without path
xml_sources_root_files = [
    'gimp.xml',
    'help-missing.xml',
    'introduction.xml',
    'key-reference.xml',
]
xml_sources_root = files(xml_sources_root_files)

subdir('appendix')
subdir('concepts')
subdir('dialogs')
subdir('filters')
subdir('glossary')
#subdir('images')
subdir('introduction')
subdir('menus')
subdir('preface')
subdir('toolbox')
subdir('tutorial')
subdir('using')
