# /src/toolbox/paint/ xml files

xml_sources_toolbox_paint = files(
    'about-common-paint-options.xml',
    'airbrush.xml',
    'blur-sharpen.xml',
    'brush-tools.xml',
    'bucket-fill.xml',
    'clone.xml',
    'common-features.xml',
    'dodge-burn.xml',
    'dynamics.xml',
    'eraser.xml',
    'gradient.xml',
    'heal.xml',
    'ink.xml',
    'MyPaint-brush.xml',
    'paintbrush.xml',
    'pencil.xml',
    'perspective-clone.xml',
    'smudge.xml',
)
