# /src/menus/view/ xml files

xml_sources_menus_view = files(
    'display-filters.xml',
    'dot-for-dot.xml',
    'flip-rotate.xml',
    'fullscreen.xml',
    'introduction.xml',
    'movetoscreen.xml',
    'navigwindow.xml',
    'new.xml',
    'padding-color.xml',
    'scroll-center.xml',
    'show-all.xml',
    'show-canvas-boundary.xml',
    'show-grid.xml',
    'show-guides.xml',
    'show-layer-boundary.xml',
    'show-menubar.xml',
    'show-rulers.xml',
    'show-sample-points.xml',
    'show-scrollbars.xml',
    'show-selection.xml',
    'show-statusbar.xml',
    'shrink-wrap.xml',
    'snap-to-bounding-boxes.xml',
    'snap-to-canvas.xml',
    'snap-to-equidistance.xml',
    'snap-to-grid.xml',
    'snap-to-guides.xml',
    'snap-to-path.xml',
    'view-black-point.xml',
    'view-color-manage-view.xml',
    'view-color-management-reset.xml',
    'view-color-management.xml',
    'view-mark-out-of-gamut.xml',
    'view-rendering-intent.xml',
    'view-soft-proof.xml',
    'zoom.xml',
)
