# fonts used

images_common_fonts = files(
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-300.eot',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-300.svg',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-300.ttf',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-300.woff',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-300.woff2',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-300italic.eot',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-300italic.svg',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-300italic.ttf',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-300italic.woff',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-300italic.woff2',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-600.eot',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-600.svg',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-600.ttf',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-600.woff',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-600.woff2',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-600italic.eot',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-600italic.svg',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-600italic.ttf',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-600italic.woff',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-600italic.woff2',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-italic.eot',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-italic.svg',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-italic.ttf',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-italic.woff',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-italic.woff2',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-regular.eot',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-regular.svg',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-regular.ttf',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-regular.woff',
    'open-sans-v13-latin_cyrillic-ext_latin-ext_cyrillic-regular.woff2',
    'open-sans-v13-latin-300.eot',
    'open-sans-v13-latin-300.svg',
    'open-sans-v13-latin-300.ttf',
    'open-sans-v13-latin-300.woff',
    'open-sans-v13-latin-300.woff2',
    'open-sans-v13-latin-300italic.eot',
    'open-sans-v13-latin-300italic.svg',
    'open-sans-v13-latin-300italic.ttf',
    'open-sans-v13-latin-300italic.woff',
    'open-sans-v13-latin-300italic.woff2',
    'open-sans-v13-latin-600.eot',
    'open-sans-v13-latin-600.svg',
    'open-sans-v13-latin-600.ttf',
    'open-sans-v13-latin-600.woff',
    'open-sans-v13-latin-600.woff2',
    'open-sans-v13-latin-600italic.eot',
    'open-sans-v13-latin-600italic.svg',
    'open-sans-v13-latin-600italic.ttf',
    'open-sans-v13-latin-600italic.woff',
    'open-sans-v13-latin-600italic.woff2',
    'open-sans-v13-latin-700.eot',
    'open-sans-v13-latin-700.svg',
    'open-sans-v13-latin-700.ttf',
    'open-sans-v13-latin-700.woff',
    'open-sans-v13-latin-700.woff2',
    'open-sans-v13-latin-700italic.eot',
    'open-sans-v13-latin-700italic.svg',
    'open-sans-v13-latin-700italic.ttf',
    'open-sans-v13-latin-700italic.woff',
    'open-sans-v13-latin-700italic.woff2',
    'open-sans-v13-latin-italic.eot',
    'open-sans-v13-latin-italic.svg',
    'open-sans-v13-latin-italic.ttf',
    'open-sans-v13-latin-italic.woff',
    'open-sans-v13-latin-italic.woff2',
    'open-sans-v13-latin-regular.eot',
    'open-sans-v13-latin-regular.svg',
    'open-sans-v13-latin-regular.ttf',
    'open-sans-v13-latin-regular.woff',
    'open-sans-v13-latin-regular.woff2',
    'questrial-v6-latin-regular.eot',
    'questrial-v6-latin-regular.svg',
    'questrial-v6-latin-regular.ttf',
    'questrial-v6-latin-regular.woff',
    'questrial-v6-latin-regular.woff2',
)
