message('pot/filters submenu')

##############

pot_filters_animation = 'animation.pot'

input_files  = xml_sources_filters_animation
output_pot = pot_filters_animation

plain_input  = xml_sources_filters_animation_files

pot_folder     = 'src/filters/animation/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/animation': input_files}

filters_animation_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_artistic = 'artistic.pot'

input_files  = xml_sources_filters_artistic
output_pot = pot_filters_artistic

plain_input  = xml_sources_filters_artistic_files

pot_folder     = 'src/filters/artistic/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/artistic': input_files}

filters_artistic_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_blur = 'blur.pot'

input_files  = xml_sources_filters_blur
output_pot = pot_filters_blur

plain_input  = xml_sources_filters_blur_files

pot_folder     = 'src/filters/blur/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/blur': input_files}

filters_blur_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_combine = 'combine.pot'

input_files  = xml_sources_filters_combine
output_pot = pot_filters_combine

plain_input  = xml_sources_filters_combine_files

pot_folder     = 'src/filters/combine/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/combine': input_files}

filters_combine_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_decor = 'decor.pot'

input_files  = xml_sources_filters_decor
output_pot = pot_filters_decor

plain_input  = xml_sources_filters_decor_files

pot_folder     = 'src/filters/decor/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/decor': input_files}

filters_decor_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_distort = 'distort.pot'

input_files  = xml_sources_filters_distort
output_pot = pot_filters_distort

plain_input  = xml_sources_filters_distort_files

pot_folder     = 'src/filters/distort/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/distort': input_files}

filters_distort_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_edge = 'edge-detect.pot'

input_files  = xml_sources_filters_edge
output_pot = pot_filters_edge

plain_input  = xml_sources_filters_edge_files

pot_folder     = 'src/filters/edge-detect/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/edge-detect': input_files}

filters_edge_detect_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_enhance = 'enhance.pot'

input_files  = xml_sources_filters_enhance
output_pot = pot_filters_enhance

plain_input  = xml_sources_filters_enhance_files

pot_folder     = 'src/filters/enhance/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/enhance': input_files}

filters_enhance_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_generic = 'generic.pot'

input_files  = xml_sources_filters_generic
output_pot = pot_filters_generic

plain_input  = xml_sources_filters_generic_files

pot_folder     = 'src/filters/generic/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/generic': input_files}

filters_generic_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_light = 'light-and-shadow.pot'

input_files  = xml_sources_filters_light
output_pot = pot_filters_light

plain_input  = xml_sources_filters_light_files

pot_folder     = 'src/filters/light-and-shadow/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/light-and-shadow': input_files}

filters_light_and_shadow_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_map = 'map.pot'

input_files  = xml_sources_filters_map
output_pot = pot_filters_map

plain_input  = xml_sources_filters_map_files

pot_folder     = 'src/filters/map/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/map': input_files}

filters_map_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_noise = 'noise.pot'

input_files  = xml_sources_filters_noise
output_pot = pot_filters_noise

plain_input  = xml_sources_filters_noise_files

pot_folder     = 'src/filters/noise/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/noise': input_files}

filters_noise_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_render = 'render.pot'

input_files  = xml_sources_filters_render
output_pot = pot_filters_render

plain_input  = xml_sources_filters_render_files

pot_folder     = 'src/filters/render/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/render': input_files}

filters_render_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)

##############

pot_filters_web = 'web.pot'

input_files  = xml_sources_filters_web
output_pot = pot_filters_web

plain_input  = xml_sources_filters_web_files

pot_folder     = 'src/filters/web/'
relative_input = []
foreach file : plain_input
    relative_input += pot_folder + file
endforeach

xml_sources_lists += { 'filters/web': input_files}

filters_web_pot = custom_target(output_pot,
    depends: [copy_authors_to_src],
    input: [input_files],
    output: [output_pot],
    command: [
        xml2pot, '@OUTPUT@', '@BUILD_ROOT@', '@SOURCE_ROOT@', relative_input,
    ],
)
