# /src/toolbox/transform/ xml files

xml_sources_toolbox_transform = files(
    'about-common-transform-options.xml',
    'align.xml',
    'cage.xml',
    'common-features.xml',
    'crop.xml',
    'flip.xml',
    'handle-transform.xml',
    'move.xml',
    'perspective.xml',
    'rotate.xml',
    'scale.xml',
    'shear.xml',
    'transform-3d.xml',
    'unified-transform.xml',
    'warp-transform.xml',
)
